name: Build and Zip

on:
  workflow_dispatch:

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
      - name: setup .net core
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x  # Replace with your desired .NET version
          
      - name: Restore and build .NET Core projects
        run: |
          dotnet restore DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/DAR-ReferenceDataUI/DAR_ReferenceDataUI.csproj
          dotnet build --configuration Release DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/DAR-ReferenceDataUI/DAR_ReferenceDataUI.csproj
          dotnet restore DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/DARRefDataTest/DARRefDataTest.csproj
          dotnet build --configuration Release DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/DARRefDataTest/DARRefDataTest.csproj
          # Add more project restore and build commands if needed

      - name: Run tests
        run: dotnet test DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/DARRefDataTest/DARRefDataTest.csproj --logger "trx;LogFileName=testresults.trx"
        # Run tests for other projects if needed



          
    
     # - name: Restore NuGet packages
      #  run: dotnet restore DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/
      #- name: Build project
      #  run: dotnet build --configuration Release
       # working-directory: DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/
      #- name: Run tests
        #run: dotnet test --no-restore --verbosity normal
     # - name: Publish
      #  run: dotnet publish DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/DAR-ReferenceDataUI.sln --configuration Release --framework netcoreapp3.1 --output ./publish --runtime win-x86  --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=tru
       # working-directory: DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/
      #- name: Restore dependencies
       # run: dotnet restore
        #working-directory: DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/  # Adjust the path

      #- name: Build
       # run: dotnet build --configuration Release
        #working-directory: DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/ # Adjust the path

      #- name: Publish
       # run: dotnet publish --configuration Release --output ./publish
        #working-directory: DARRefMasterUI-DP-3166/DAR-ReferenceDataUI/  # Adjust the path

      #- name: Create zip
       # run: |
        #  zip -r build.zip ./publish
         # mv build.zip $GITHUB_WORKSPACE/build2208.zip
