name: Naveen Build and zip

on:
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: windows-latest  # Use the Windows runner


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: dotnet restore Main-Build

    - name: Restore dependencies
      run: msbuild /restore

    - name: Build .NET code
      run: msbuild /p:Configuration=Release Main-Build

    - name: Publish .NET code
      run: msbuild /t:Publish /p:Configuration=Release /p:OutputPath=./publish Main-Build
 
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-code-artifact
        path: ./publish
