name: Copy Git to Lighsail

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: install sshpass
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y sshpass
          sudo apt-get update
          
      - name: Create ~/.ssh directory
        run: mkdir -p ~/.ssh
        
      - name: Update known_hosts file
        run: |
          # Replace the placeholders with actual values
          WINDOWS_SERVER_IP="3.110.130.37"

          # Update known_hosts file with the new host key
          echo "$WINDOWS_SERVER_IP $(ssh-keyscan -t rsa $WINDOWS_SERVER_IP 2>&1)" >> ~/.ssh/known_hosts
      - name: Files Check
        run: |
           ls
      - name: Copy files to Windows server
        run: |
          # Replace the placeholders with actual values
          #WINDOWS_SERVER_IP="3.110.130.37"
          #WINDOWS_SERVER_USER="Administrator"
          #SOURCE_FOLDER="${{ github.workspace }}"
          #DESTINATION_FOLDER="C:/test3"

          # Use scp with converted private key for authentication
          sshpass -vvv -p 'akqR3XeigseYHlWxD$T8ZtpWu&T*BkJm' scp -o StrictHostKeyChecking=no test.txt Administrator@3.110.130.37:/C:/test3
