name: Deploy Naveen lightsail Refmaster Pipeline

on:
  workflow_dispatch:
    inputs:
      BuildName:
        description: 'Enter The Build Name'
        required: true

env:
  DESTINATION_FOLDER_CONFIG: "C:/DeploymentFiles/ReleaseFolder/Web.config"
  BuildName: '${{ github.event.inputs.BuildName }}'

jobs:
  build-deploy:
    runs-on: RefDeployDev
    steps:
    
    - name: Checking Build File ${{ github.event.inputs.BuildName }} at Version Location. => THIS STEP WILL FAIL IF NO REQUESTED FILE AT LOCATION
      run:  |
        $sourceDirectory = "C:\DeploymentFiles\VersionFolder"
        $targetDirectory = "C:\DeploymentFiles\ReleaseFolder"
        $buildFileName = $env:BuildName
        $foundBuild = Get-ChildItem -Path $sourceDirectory -Recurse -Directory | Where-Object { $_.Name -eq $BuildfileName }
        if ($foundBuild) {
        Write-Host "Builed found at $($foundBuild.FullName)"
        
    - name: Stop IIS server
      run: |
        Stop-Service -Name W3SVC; Get-Service -Name W3SVC

    - name: Remove Old files from deploy location
      run: |
        Remove-Item C:\DeploymentFiles\ReleaseFolder\* -Recurse



    - name: Deploying build on server BUILD NAME IS ========> ${{ github.event.inputs.BuildName }}
      run: |
        Get-ChildItem
        $sourceDirectory = "C:\DeploymentFiles\VersionFolder"
        $targetDirectory = "C:\DeploymentFiles\ReleaseFolder"
        $buildFileName = $env:BuildName
        $foundBuild = Get-ChildItem -Path $sourceDirectory -Recurse -Directory | Where-Object { $_.Name -eq $BuildfileName }
        if ($foundBuild) {
        Write-Host "Builed found at $($foundBuild.FullName)"

                
        Copy-Item -Path $foundBuild.FullName -Destination $targetDirectory -Recurse -Force
        Write-Host "File copied successfully."
        
        } else {
         Write-Host "File not found. Failing the workflow."
         exit 1
          }

    
    
        
