name: Deploy Naveen lightsail Refmaster Pipeline

on:
  workflow_dispatch:
    inputs:
      BuildName:
        description: 'Enter The Build Name'
        required: true

env:
  DESTINATION_FOLDER_CONFIG: "C:/DeploymentFiles/ReleaseFolder/Web.config"
  BuildName: '${{ github.event.inputs.BuildName }}'
  sourceDirectory: "C:/DeploymentFiles/VersionFolder"
  targetDirectory: "C:/DeploymentFiles/ReleaseFolder"
  BuildInfoDir: "C:/DeploymentFiles/BuildInfo"
  
jobs:
  build-deploy:
    runs-on: RefDeployDev
    steps:
    
    - name: Checking Build File ${{ github.event.inputs.BuildName }} at Version Location. => THIS STEP WILL FAIL IF NO REQUESTED FILE AT LOCATION
      run:  |
        $buildFileName = $env:BuildName
        $foundBuild = Get-ChildItem -Path $env:sourceDirectory -Recurse -Directory | Where-Object { $_.Name -eq $buildfileName }
        if ($foundBuild) {
        Write-Host "Builed found at $($foundBuild.FullName)"
                } else {
         Write-Host "File not found. Failing the workflow."
         exit 1
          }
        
    - name: Stop IIS server
      run: |
        Stop-Service -Name W3SVC; Get-Service -Name W3SVC

    - name: Remove Old files from deploy location
      run: |
        Remove-Item $env:targetDirectory\* -Recurse



    - name: Deploying build on server BUILD NAME IS ========> ${{ github.event.inputs.BuildName }}
      run: |

         $buildFileName = $env:BuildName
         $foundBuild = Get-ChildItem -Path $env:sourceDirectory -Recurse -Directory | Where-Object { $_.Name -eq $BuildfileName }
                
          Copy-Item -Path $foundBuild.FullName -Destination $env:targetDirectory -Recurse -Force
          Write-Host "build deployed successfully."
        
         } else {
          Write-Host "File not found. Failing the workflow."
          exit 1
           }
   
    - name: Adding Build Info
      run: |
          $buildInfo = "Build Number: $($env:BuildName)`r`  Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
          $buildInfoFilePath = Join-Path -Path $BuildInfoDir -ChildPath "build_info.txt"

          Add-Content -Path $buildInfoFilePath -Value $buildInfo

          Write-Host "Build information appended to $buildInfoFilePath"
          } else {
          Write-Host "Build info missed"
          exit 1
          }
