name: Naveen Build and zip

on:
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: windows-latest  # Use the Windows runner


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore Main-Build

    - name: Restore dependencies
      run: dotnet restore Main-Build
    - name: Restore dependencies2
      run: msbuild /restore Main-Build

    - name: Build .NET code
      run: msbuild /p:Configuration=Release Main-Build

    - name: Publish .NET code
      run: msbuild /t:Publish /p:Configuration=Release /p:OutputPath=./publish Main-Build

    - name: Create temporary directory
      run: mkdir temp_artifact

    - name: Copy published artifact to temp directory
      run: Copy-Item -Path "./publish" -Destination temp_artifact -Recurse

    - name: List files in temp directory
      run: dir temp_artifact
    #- name: Upload build artifacts
     # uses: actions/upload-artifact@v2
    #  with:
     #   name: build-artifacts
     #   path: Main-Build/publish/publish  # Change this to the correct path
