name: Parallel Jobs Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: LSWinLabel

    steps:
    - name: Job 1 Step 1
      run: echo "Running Job 1 Step 1"

    - name: Job 1 Step 2
      run: echo "Running Job 1 Step 2"

  job2:
    runs-on: LSWinLabel

    steps:
    - name: Job 2 Step 1
      run: echo "Running Job 2 Step 1"

    - name: Job 2 Step 2
      run: echo "Running Job 2 Step 2"
