name: Build and Publish .NET Website

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'  # Change this to your desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build .NET website
      run: dotnet build --configuration Release
      

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: website-artifact
        path: DARRefMasterUI-DP-3166/DAR-ReferenceDataUI  # Change this to the directory containing the built files
