name: Move Build to deploy location

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Create ~/.ssh directory
        run: mkdir -p ~/.ssh

      - name: Update known_hosts file
        run: |
          WINDOWS_SERVER_IP="3.110.130.37"
          echo "$WINDOWS_SERVER_IP $(ssh-keyscan -t rsa $WINDOWS_SERVER_IP 2>&1)" >> ~/.ssh/known_hosts

      - name: Copy files to Windows server
        run: |
          # Replace the placeholders with actual values
          SOURCE_FILE=$(ls -t | head -n1)  # Get the latest file in the directory
          # SSH into the server and execute commands
          sshpass -p 'akqR3XeigseYHlWxD$T8ZtpWu&T*BkJm' ssh -o StrictHostKeyChecking=no "Administrator@3.110.130.37" 
            # Move the file to a different location
            cp "C:/test3/$SOURCE_FILE" "C:/test2/"

            # Restart IIS service
            Restart-Service -Name W3SVC
