name: Move File to Different Location

on:
  workflow_dispatch:
  #workflow_run:
   # workflows: ["Copy Git to Lighsail"]
    #types:
     # - completed

jobs:
  move-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Create ~/.ssh directory
        run: mkdir -p ~/.ssh

      - name: Update known_hosts file
        run: |
          WINDOWS_SERVER_IP="3.110.130.37"
          echo "$WINDOWS_SERVER_IP $(ssh-keyscan -t rsa $WINDOWS_SERVER_IP 2>&1)" >> ~/.ssh/known_hosts

      - name: Move File to Different Location
        run: |
          # Replace the placeholders with actual values
          WINDOWS_SERVER_USER="Administrator"
          WINDOWS_SERVER_IP="3.110.130.37"
          SOURCE_FILE="C:\test3\test.txt"
          DESTINATION_FOLDER="C:\test2\"

          # Use SSH to move the file to a different location on the remote server
          sshpass -p 'akqR3XeigseYHlWxD$T8ZtpWu&T*BkJm' ssh -o StrictHostKeyChecking=no "$WINDOWS_SERVER_USER@$WINDOWS_SERVER_IP" 
          Move-Item -Path '$SOURCE_FILE' -Destination '$DESTINATION_FOLDER'
