name: .NET Build (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: LSWinLabel

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your code from the repository

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1  # This step sets up the .NET SDK on the runner
      with:
        dotnet-version: '5.0'  # Specify the .NET SDK version you want to use

    - name: Clean the NuGet packages
      run: |
        cd Main-Build
        nuget restore

    - name: Build with .NET
      run: |
       cd Main-Build
       dotnet build --configuration Release  # Adjust the build command as needed
